$ANSIBLE_VAULT;1.1;AES256
65663233666439663430323133316539373431386332373434396135623730343866313034336466
6463643264333939306430623536653966623362333439660a626635643631336536316132356165
38613064386164383338353462323134356562663036373736613563343338353736616130303862
6538396162303434610a343531666464346535623535366665383264393732666262626431646533
39636538376132636430303232633365666231366632353164623534363939363861393363366462
31366661386433386663313261303238316164613736623563316130373639316138373235616233
33363739656239326536663966616232393739373261626663303532346333343833393030343535
37373630623365633563656339346263383030663238323365613236616163313239353134396264
33386366353530376662613839636333613335303038663265623730373564306361
