---

__promtail_scrape_configs_2:
  - job_name: gitlab
    static_configs:
      - targets:
          - localhost
        labels:
          job: gitlab
          __path__: /var/log/gitlab/gitlab-rails/production_json.log
