---

prometheus_blackbox_icmp_targets:
  - "{{ wireguard_ip }}"
  - "{{ ansible_host }}"
prometheus_node_targets: []

mt_firewall_address_lists:
  - address: "{{ ansible_host }}"
    list: allow-smtp
  - address: "{{ ansible_host }}"
    list: allow-rsyslog
  - address: "{{ wireguard_ip }}"
    list: allow-rsyslog
