$ANSIBLE_VAULT;1.1;AES256
32643966386135346331623365343466633235313162383034316462373565333438306562353466
6566383736356534376332616337373135633664356431300a663239346335336330643962366663
38306232383531313661393735373265323930383162656334663339376561653132353765353631
6135333936303835390a646534313064653132363837326638356162313934363465626532323036
32313434356564313232303737613933656166663762343733646532363935626164666335386666
32373039376135323436333530366431323762383435653730356263386333313333663737306436
62663262383532313033616536613130303764383739346131363433613830656435653062343064
63343731323662613364613633353565613566333333623666626562326138313334346334396531
3564
