$ANSIBLE_VAULT;1.1;AES256
65633832346630653031343137383164396533646463663037626464393662323037313538633465
6562316638643432323563393263346163326633306233300a363833663734646635306465633866
61306566656265333332383466663963613234303561343334663230643235393737316638313138
3338316630643333620a363637336566623031623164303435653336653939663038343162343433
37363564333265346561396535366434653966313562326461366563666664336131633165663238
32633331356338346366663335653531643330623130323965363566626138333937346666623433
39356231633263366135343931653939373461613136393133356536313035623163636636643861
66306239356438653239323033353832656435356666313765336533336661383439373061396434
35623737653836346161653037336336363362396563373634373035323030303735666238666665
30303433336535373233636633366533353939613535666563386434326335373764316433383335
35373934653939663030346334323162643635326163383733376230386432396530323264643536
37326231343234366265356434663862353837333234383233343632663566303430356562616438
32326232346266366163646130653539313261363334316537303162613737326637313730346165
3161366535336162363839636461333931316563633136303162
